# Generated by Django 5.0.2 on 2024-02-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='all_posts',
            field=models.IntegerField(default=0),
        ),
    ]
